In [36]:
import pandas as pd
import numpy as np

In [37]:
df=pd.read_csv('watches.csv')
df.head(11)

,title,price,rating,oprice,brand
0,USM ID116 Smart Watch Smart Bracelet Fitness T...,329,4.4,₹329,USM
1,boAt Xtend Smartwatch Batman Edition with Alex...,"1,299",4.1,"₹1,299",boAt
2,boAt Flash Edition Smart Watch with Activity T...,"1,499",4.0,"₹1,499",boAt
3,Noise ColorFit Pulse Grand Smart Watch with 1....,"1,299",4.0,"₹1,299",Noise
4,Digital Sports Multi Functional Black Dial Wat...,284,3.8,₹284,Shocknshop
5,Silicone Strap Analog Wrist Watch for Men (Bla...,397,4.0,₹397,LOUIS DEVIN
6,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...","1,799",4.3,"₹1,799",Fire-Boltt
7,SHREENOVA® ID116 Plus Bluetooth Fitness Smart ...,399,3.1,₹399,Generic
8,"boAt Wave Prime47 Smart Watch with 1.69"" HD Di...","1,199",3.4,"₹1,199",boAt
9,Tokdis MX-1 Pro Bluetooth Calling Smartwatch -...,799,3.1,₹799,Tokdis
10,Analog Day Date Functioning Stainless Steel Ch...,319,3.8,₹319,TIMEWEAR

In [38]:
def clean_price_column(price):
    if isinstance(price,str):
        price=price.replace(',','').replace('₹','')
        return price
    return price

In [40]:
def clean_rating_column(rating):
    if isinstance(rating,str):
        if((len(rating)==3) and '.' in rating):
            return float(rating)
        return np.nan
    return float(rating)

In [39]:
df['New_Price']=df['price'].apply(clean_price_column)

In [41]:
df['New_Rating']=df['rating'].apply(clean_rating_column)

In [42]:
df['New_Oprice']=df['oprice'].apply(clean_price_column)

In [44]:
df

,title,price,rating,oprice,brand,New_Price,New_Rating,New_Oprice
0,USM ID116 Smart Watch Smart Bracelet Fitness T...,329,4.4,₹329,USM,329,4.4,329
1,boAt Xtend Smartwatch Batman Edition with Alex...,"1,299",4.1,"₹1,299",boAt,1299,4.1,1299
2,boAt Flash Edition Smart Watch with Activity T...,"1,499",4.0,"₹1,499",boAt,1499,4.0,1499
3,Noise ColorFit Pulse Grand Smart Watch with 1....,"1,299",4.0,"₹1,299",Noise,1299,4.0,1299
4,Digital Sports Multi Functional Black Dial Wat...,284,3.8,₹284,Shocknshop,284,3.8,284
...,...,...,...,...,...,...,...,...
301,IZU Kids Cartoon Character Waterproof Superher...,499,3.2,₹499,IZU,499,3.2,499
302,Analog Silver Dial Children's Watch-NLC4006PP0...,775,4.5,₹775,Zoop,775,4.5,775
303,Watches: The History of Time: Signature Timepi...,0,3.6,₹0,Samuel Johnson,0,3.6,0
304,Economy Analog Black Dial Men's Watch-NM3039SL...,"1,895",4.1,"₹1,895",Fastrack,1895,4.1,1895
305,Super Fibre Digital Grey Dial Men's Watch-NL87...,585,4.1,₹585,Sonata,585,4.1,585

In [45]:
df.to_csv('watches_clean.csv',index=False)